---
title: "A Project for Reproducible Research"
subtitle: "PDF and LaTeX"
author: 
  - Adnan Sevinc (437971) 
  - Le Nhat Tung (426246)
  - Temmuz Burak Yavuzer (444130)
date: today
format: 
  pdf: 
    citation_package: natbib
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    smooth-scroll: true
documentclass: article
number-sections: true
number-depth: 2
title-block-banner: true
fontsize: 11pt
geometry: margin=1in
latex-tinytex: false
output: html_document
---


------------------------------------------------------------------------

# Executive Summary

::: {.justify}

The aim of this project is to assess the validity of the published [article](https://www.sciencedirect.com/science/article/abs/pii/S1364032116000848)
from a prominent publisher. namely, to check whether the published article is
consistent or not.  

:::
     
::: {.justify}

We decided to employ the reproducible research on the selected article
because of the fact that there are many articles in the literature in order to
investigate the relationship between energy consumption and energy use and
their result is somehow contradictory. The relationship between energy
consumption and carbon dioxide (indicator of environmental deterioration)
observed differently due to either dataset or/and region. Considering all of the
inconsistency it will be a great experience for us to check its validity.  

:::


The dataset of the article obtained from [World Data Bank Indicator](http://data.worldbank.org/indicator)   

Lastly related code and report published in [repository](RRProject_426246_437971_444130)

------------------------------------------------------------------------

# Install Required Packages

```{r}
if (!require("pacman")) install.packages("pacman")

pacman::p_load(                                
               "ggplot2",
               "tidyverse",
               "dplyr",
               "wbstats",
               "gmm",
               "reticulate",
               "data.table",
               "panelvar",
               "pdynmc",
               "tidyr",
               "plm",
               "pastecs",
               "stargazer"
)


Sys.setlocale("LC_TIME", "English")

```

------------------------------------------------------------------------

# Dataset

Following variables used during modeling process:

1.    CO2 emissions (metric tons per capita)
2.    Energy use (kg of oil equivalent per capita)
3.    GDP per capita (constant 2015 US$)
4.    Urban population (% of total population)
5.    Trade (% of GDP)

for the time period spanning from 1990 to 2012.

------------------------------------------------------------------------

# Import Dataset

We imported dataset directly from WDI using **wbstats** packages.

```{r}
my_indicators <- c(                         
  C = "EN.ATM.CO2E.PC",  
  E ="EG.USE.PCAP.KG.OE",  
  Y = "NY.GDP.PCAP.KD", 
  URB = "SP.URB.TOTL.IN.ZS", 
  TR = "NE.TRD.GNFS.ZS" 
)

world_stats <- wb_data(my_indicators, start_date = 1990, end_date = 2012) 
```

C, E, Y, URB, and TR represent CO2 emissions, energy use, GDP per capita, urban population, and trade, respectively.


------------------------------------------------------------------------

# Data Preparation

```{r}
names(world_stats)
```
As seen in the output above, the iso2c and iso3c columns have also been imported into the data environment. However, these columns are not necessary for the analysis, so we will remove them.

##   Discard the irrelevant columns

```{r}
#| echo: false
df <- world_stats[,3:length(names(world_stats))]
```

iso2c and iso3c columns eliminated from the model.

```{r}
#| echo: false
cat("The dataset consist of",length(setdiff(names(df),c("country","date"))),"variables and",nrow(df), "observations.")
```

We used the following variables to construct a panel data model

```{r}
#| echo: false
print(setdiff(names(df),c("country","date")))
```

##   Completeness check


```{r}
#| echo: false
print(colSums(is.na(select(df,c(E,C,TR,Y,URB)))))
```

As it can be observed, we do have missing values in our dataset.

The article does not mention handling missing values; therefore, we will use complete cases, specifically the dataset without any missing values (NAs).

```{r}
#| echo: false
df <- df[complete.cases(df),]  
```

##    Create a Variable

To construct a model for the Environmental Kuznets Curve (EKC), we generated a squared per capita variable.

We will create $y^2$

```{r}
df$logY2 = log(df$Y)*log(df$Y)
```

## Create an ID column for Panel data analysis based on the countries

For the panel data analysis, we generated an identifier based on the countries.

```{r}
df <- data.table(df)
df[, id := .GRP, by = country]
```

## Split dataset to  based on the regions

We divided the dataset into European and North Asian region countries to build a model that incorporates these regions along with the entire panel data.    

These countries has been indicated in the article.


###   European and North Asian region Countries

```{r}
EuropeAsia = c("Albania", "Belgium", "Bulgaria", "Denmark", "France",
"Germany", "Greece", "Hong Kong SAR, China", "Korea, Rep.", "Hungary", "Iceland", "Ireland",
"Italy", "Japan", "Luxembourg", "Netherlands", "Norway", "Portugal",
"Spain", "Sweden", "Switzerland", "United Kingdom")

dfEuropeAsia <- df[df$country %in% EuropeAsia,]

sort(unique(dfEuropeAsia$country))
```

```{r}
paste0("Number of European and North Asian region countries: ",length(unique(dfEuropeAsia$country)))
```

Please be aware that "Hong Kong SAR, China" has been omitted from our reproducible research (after focusing exclusively on complete cases) due to the unavailability of its CO2 emission data.

###   Latin American and Caribbean region Countries

```{r}
LACarrb = c("Argentina", "Bolivia", "Brazil", "Nicaragua", "Chile",
"Costa Rica", "Ecuador", "Guatemala", "Honduras", "Mexico", "Panama",
"Paraguay", "Peru", "Uruguay", "Venezuela, RB")

dfLACarrb <- df[df$country %in% LACarrb,]

sort(unique(dfLACarrb$country))

paste0("Number of Latin American and Caribbean region: ",length(unique(dfLACarrb$country)))

```

Please be aware that "Venezuela, RB" has been omitted from our reproducible research (after focusing exclusively on complete cases) due to the unavailability of its GDP per capita dataset.


###   Middle Eastern, North African, and sub-Saharan region Countries

```{r}

MeNoAfrSub= c("Algeria", "Botswana",
"Cameroon", "Congo, Dem. Rep.", "Cote d'Ivoire", "Ethiopia", "Gabon", "Ghana",
"Egypt, Arab Rep.", "Iran, Islamic Rep.", "Jordan", "Kenya", "Morocco", "Mozambique", "South Africa",
"Senegal", "Sudan", "Syrian Arab Republic", "Togo", "Tunisia","Zambia")

dfMeNoAfrSub <- df[df$country %in% MeNoAfrSub,]

sort(unique(dfMeNoAfrSub$country))

paste0("Number of Middle Eastern, North African, and sub-Saharan region: ",length(unique(dfMeNoAfrSub$country)))

```

###   Creating a Global Panel Countries

```{r}

globalPanel= c(EuropeAsia,LACarrb,MeNoAfrSub)

dfglobalPanel <- df[df$country %in% globalPanel,]

sort(unique(dfglobalPanel$country))

paste0("Number of Global Panel: ",length(unique(dfglobalPanel$country)))

```

------------------------------------------------------------------------

# Reproducible Outputs - Exploratory Data Analysis

##    Output of Table 2 page: 1105

```{r}
#| echo: false
library(pastecs)
statsdfEuropeAsia = round(stat.desc(dfEuropeAsia[,c("E","Y","C","URB","TR")]),3) 
statsdfEuropeAsiaTable2 = statsdfEuropeAsia[c("mean", "std.dev", "coef.var"),]
print(statsdfEuropeAsiaTable2)

```


##    Output of Table 2 page: 1105

```{r}
#| echo: false
library(pastecs)
statsdfLACarrb = round(stat.desc(dfLACarrb[,c("E","Y","C","URB","TR")]),3) 
statsdfLACarrbTable2 = statsdfLACarrb[c("mean", "std.dev", "coef.var"),]
print(statsdfLACarrbTable2)
```

##    Output of Table 2 page: 1105

```{r}
#| echo: false
library(pastecs)
statsdfMeNoAfrSub = round(stat.desc(dfMeNoAfrSub[,c("E","Y","C","URB","TR")]),3) 
statsdfMeNoAfrSubTable2 = statsdfMeNoAfrSub[c("mean", "std.dev", "coef.var"),]
print(statsdfMeNoAfrSubTable2)
```

##    Output of Table 3 page: 1106

```{r}
#| echo: false
dflogCorr <- dfglobalPanel[, c("C","Y","E")]
dflogCorr[] <- lapply(dflogCorr, log)
dflogCorr[, c("URB","TR")] <- dfglobalPanel[, c("URB","TR")]
corrMatrix <- cor(dflogCorr)
corrMatrix
```

```{r}
#| echo: false
upper<-corrMatrix
upper[upper.tri(corrMatrix)]<-""
upper<-as.data.frame(upper)
upper
```
